response greeting: "欢迎来到电商客服。您可以查询订单、物流、退货退款或商品信息。"
response order_help: "查询订单请提供订单号或注册手机号，我们将帮您查找订单信息。"
response logistics_help: "物流查询请提供运单号或订单号以便跟踪配送状态。"
response refund_help: "退货退款请先确认订单是否符合退货条件，我们会为您指引下一步操作。"
response product_help: "商品咨询请提供商品名称或ID，支持查询价格与库存信息。"
response promo_help: "当前优惠请关注活动页面或联系客服了解更多。"
response order_not_found: "抱歉，未找到相关订单。"